name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test script
        run: echo "Add your test script here"

# env:
#   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#   TF_VAR_token: ${{ secrets.TOKEN }}
#   TF_VAR_secret: ${{ secrets.SECRET }}
#   TF_VAR_endpoint: "https://api.clever-cloud.com"
#   TF_VAR_organisation: ${{ secrets.ORGANISATION }}
#   TF_VAR_secret_key: ${{ secrets.APPLICATION_SECRET_KEY }}
#   TF_VAR_admin_password: ${{ secrets.ADMIN_PASSWORD }}
#   TF_VAR_admin_user: ${{ secrets.ADMIN_USER }}

# jobs:
#   ##############################################################################
#   #                          terraform PLAN                                    #
#   ##############################################################################
#   terraform-plan:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Set up Terraform
#         uses: hashicorp/setup-terraform@v3
#         with:
#           terraform_version: 1.6.6

#       - name: Terraform Init apply
#         run: |
#           terraform init
#         working-directory: terraform/

#       - name: Terraform Format Check
#         run: terraform fmt -check
#         working-directory: terraform/

#       - name: Terraform Validate
#         run: terraform validate
#         working-directory: terraform/

#       - name: Terraform Plan
#         run: terraform plan
#         working-directory: terraform/

#   ##############################################################################
#   #                          terraform APPLY                                   #
#   ##############################################################################
#   terraform-apply:
#     runs-on: ubuntu-latest
#     environment: terraform_holder
#     needs: [terraform-plan]
#     steps:
#       - uses: actions/checkout@v4

#       - uses: hashicorp/setup-terraform@v3
#         with:
#           terraform_version: 1.6.6

#       - name: Terraform Init apply
#         run: |
#           terraform init
#         working-directory: terraform/

#       - run: terraform apply -auto-approve
#         working-directory: terraform/
